const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Project = sequelize.define('Project', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    // Removed unique constraint on name, ID will be unique key
  },
  color: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      is: /^#[0-9A-F]{6}$/i // Hex color validation
    }
  },
  // New field for the unique ID generated by the device
  device_project_id: {
    type: DataTypes.STRING,
    allowNull: true, // Allow null for existing projects before backfill/first webhook
    unique: true     // This is the new unique identifier
  }
}, {
  // Enable timestamps (created_at, updated_at)
  timestamps: true,
  // Use snake_case instead of camelCase for attributes
  underscored: true
});

module.exports = Project; 