#ifndef PROJECT_DATA_H
#define PROJECT_DATA_H

#include <Arduino.h>
#include <vector>

// Maximum number of projects that can be stored
const int MAX_PROJECTS = 20;

// NVS key for storing the JSON string representing the list of projects
extern const char *NVS_PROJECTS_KEY;

// NVS key for storing the index of the last selected project
extern const char *NVS_LAST_PROJECT_KEY;

// NVS key for storing the next project ID counter
extern const char *NVS_PROJECT_ID_COUNTER_KEY;

// Represents a single project with a name and associated color (hex string)
struct Project
{
  String name;
  String color;             // Expected format: "#RRGGBB"
  String device_project_id; // Unique ID generated by the device (e.g., "ChipID-Counter")
};

// Type alias for a list of projects
using ProjectList = std::vector<Project>;

#endif // PROJECT_DATA_H